### ISSUE TITLE
Move the public site over to React

### ISSUE THREAD

**Issue by joshghent** [OTRChat/NodeChat#11]
The old site uses jquery and static assets, let's make it a little nicer with react. You can quickly boilerplate this with create-react-app

**Comment by coreyjjames** [comment]
Hey, @joshghent I can set this up for you.

**Comment by dbrudner** [comment]
I'd like to contribute to this if you're looking for more help.

**Comment by coreyjjames** [comment]
@dbrudner That cool with me if you help. Just waiting for @joshghent reply

**Comment by joshghent** [comment]
@coreyjjames @dbrudner Hi both, the PR's will count for each of you without being merged. Perhaps to combine your efforts @coreyjjames could make a start on it, then @dbrudner could also do it. That way you both get a PR! What do you say?
