### ISSUE TITLE
Show online users down the right hand side

### ISSUE THREAD

**Issue by joshghent** [OTRChat/NodeChat#4]
Create a collapsable side bar that displays all online users.

**Comment by shubhamguptaji** [comment]
you want a collapsible sidebar on left side or right side?

**Comment by joshghent** [comment]
@shubhamguptaji I think the right side! What do you think?

**Comment by shubhamguptaji** [comment]
I think left side will be better

**Comment by shubhamguptaji** [comment]
Can I fix this issue?

**Comment by joshghent** [comment]
@shubhamguptaji Go for it, do whatever you think is right
