### ISSUE TITLE
Switch all CSS to either vanilla CSS or SASS

### ISSUE THREAD

**Issue by dnguneratne** [OTRChat/NodeChat#46]
Currently nodeChatReact has sass and css. We should stick to one. What are some thoughts about this?

Related to #36

**Comment by AlexeiGitH** [comment]
I'd go with css, but that's just a personal preference.

**Comment by coreyjjames** [comment]
I think css for now, down the road if we need things like variable we can move to sass. @dnguneratne do you want to do this?

**Comment by dnguneratne** [comment]
Yes, I can do this as part of the clean up as well.

**Comment by joshghent** [comment]
Yeah I think SASS is best for expanding, it allows you to reuse rules a lot more

**Comment by dnguneratne** [comment]
I personally prefer SASS as well. However, @coreyjjames, @AlexeiGitH prefers CSS. After @joshghent's comment do you still feel we should stick to CSS?

**Comment by coreyjjames** [comment]
If we use sass, Is there a way of linking up the react start command to compile the sass as well?

**Comment by dnguneratne** [comment]
@coreyjjames, yes, it compiles with the start command.

In hindsight, looking at React docs they recommend using CSS: https://facebook.github.io/create-react-app/docs/adding-a-sass-stylesheet
