### ISSUE TITLE
Increase minimum chat message bubble size

### ISSUE THREAD

**Issue by dnguneratne** [OTRChat/NodeChat#54]
![image](https://user-images.githubusercontent.com/8231763/48329094-1cff5f80-e615-11e8-893a-f0d12506b3e0.png)

Part of the time get slightly cut off if the message is too small. I suggest we increase the bubble size a bit.

**Comment by joshghent** [comment]
Yeah it would be best if this was dynamic. Alternatively, we could abandon the bubbles entirely and change it to be more like irc or something. Have a look around on dribbble perhaps

**Comment by mphan6** [comment]
I'll take a look on the sizing for the time being (:
