### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by joshghent** [OTRChat/NodeChat#6]
Add logging of usage with Google analytics and APM software (like New relic or Datadog)

**Comment by dnguneratne** [comment]
New relic and Datadog seems to be paid applications. Is this for server-side logging? What about Winston.js or bunyan.js?

**Comment by joshghent** [comment]
Ideally we should log metrics around usage so we can track what features people are using and stuff, but in the name of privacy, let's just keep the logging only to capture errors with something like Bugsnag.
Then we can use bunyan (I personally prefer it) to log to papertrail as they have a good free plan. We can log when someone sends a message and anything else that might be useful in debugging issues. We want to make sure not to reveal any user information though.
