### ISSUE TITLE
Consider renaming this repo

### ISSUE THREAD

**Issue by dnguneratne** [OTRChat/NodeChat#60]
Seeing as the other one is called OTRChat/server perhaps this should be renamed to OTRChat/client? Or perhaps OTRChat/NodeChat-Client and OTRChat/NodeChar-Server?

**Comment by joshghent** [comment]
@dnguneratne Yeah good idea, makes sense I suppose. It was named that previously when it was under my name. I would say the only down side of this is that everyone has to go and update their git remote URL's on their machine, so unless it's causing real confusion, I would leave it as it is for now.
