### ISSUE TITLE
Create a gitter channel

### ISSUE THREAD

**Issue by joshghent** [OTRChat/NodeChat#66]
Might be useful for discussing things

P.S. I updated the readme with URL 👍 https://github.com/OTRChat/NodeChat/commit/3732928b2b9decc37e1218884bf6cc5570519928

**Comment by coreyjjames** [comment]
@joshghent I normally use slack, here's a link to the [slack channel](https://join.slack.com/t/nodechatapp/shared_invite/enQtNDcxNjgzODE1ODA5LTkzZDg4NWVkNzE3NDZjYzQ3MTM5Mzg4NWZlYmJmMGNmMjJmZmU2OTAwNjJiYWYwNDUyYWE5YWQ0MGE0YWIzYjY).

**Comment by joshghent** [comment]
@coreyjjames Haha yes me too! Awesome, more than happy to use slack!
